# Generated by Django 2.1.7 on 2019-03-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='date',
        ),
        migrations.RemoveField(
            model_name='list',
            name='time',
        ),
    ]
